// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0
// source: history.sql

package repositories

import (
	"context"
)

const saveHistory = `-- name: SaveHistory :one
INSERT INTO "answer_history"
    ("id", "slide_id", "raw_question", "raw_answer", "num_chosen")
VALUES
    ($1, $2, $3, $4, $5)
RETURNING id, slide_id, raw_question, raw_answer, num_chosen, created_at, updated_at
`

type SaveHistoryParams struct {
	ID          string `json:"id"`
	SlideID     string `json:"slide_id"`
	RawQuestion string `json:"raw_question"`
	RawAnswer   string `json:"raw_answer"`
	NumChosen   int32  `json:"num_chosen"`
}

func (q *Queries) SaveHistory(ctx context.Context, arg SaveHistoryParams) (AnswerHistory, error) {
	row := q.db.QueryRowContext(ctx, saveHistory,
		arg.ID,
		arg.SlideID,
		arg.RawQuestion,
		arg.RawAnswer,
		arg.NumChosen,
	)
	var i AnswerHistory
	err := row.Scan(
		&i.ID,
		&i.SlideID,
		&i.RawQuestion,
		&i.RawAnswer,
		&i.NumChosen,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
