// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package repositories

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteUser(ctx context.Context, email string) error
	GetUser(ctx context.Context, userID string) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	ListUser(ctx context.Context, arg ListUserParams) ([]User, error)
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) (User, error)
	UpdateSocialID(ctx context.Context, arg UpdateSocialIDParams) (User, error)
	Verify(ctx context.Context, email string) (User, error)
}

var _ Querier = (*Queries)(nil)
