// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package repositories

import (
	"context"
)

type Querier interface {
	AddMemberToGroup(ctx context.Context, arg AddMemberToGroupParams) error
	CheckUserInGroup(ctx context.Context, arg CheckUserInGroupParams) (bool, error)
	CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteGroup(ctx context.Context, groupID string) error
	DeleteUser(ctx context.Context, email string) error
	GetGroup(ctx context.Context, groupID string) (Group, error)
	GetRoleInGroup(ctx context.Context, arg GetRoleInGroupParams) (string, error)
	GetUser(ctx context.Context, userID string) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserGroup(ctx context.Context, arg GetUserGroupParams) (UserGroup, error)
	ListEmailInGroup(ctx context.Context, groupID string) ([]string, error)
	ListGroupJoined(ctx context.Context, userID string) ([]ListGroupJoinedRow, error)
	ListGroupOwned(ctx context.Context, userID string) ([]ListGroupOwnedRow, error)
	ListMemberInGroup(ctx context.Context, groupID string) ([]ListMemberInGroupRow, error)
	ListUser(ctx context.Context, arg ListUserParams) ([]User, error)
	RemoveMemberFromGroup(ctx context.Context, arg RemoveMemberFromGroupParams) error
	UpdateAvatarUrl(ctx context.Context, arg UpdateAvatarUrlParams) (User, error)
	UpdateMemberRole(ctx context.Context, arg UpdateMemberRoleParams) error
	UpdateMemberStatus(ctx context.Context, arg UpdateMemberStatusParams) error
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) (User, error)
	UpdateProfile(ctx context.Context, arg UpdateProfileParams) (User, error)
	UpdateSocialID(ctx context.Context, arg UpdateSocialIDParams) (User, error)
	Verify(ctx context.Context, email string) (User, error)
}

var _ Querier = (*Queries)(nil)
