// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0
// source: question.sql

package repositories

import (
	"context"
)

const createQuestion = `-- name: CreateQuestion :one
INSERT INTO "question" (
    id,
    slide_id,
    index,
    raw_question,
    meta,
    long_description,
    type,
    created_at,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    now(),
    now()
)
RETURNING id, slide_id, index, raw_question, meta, long_description, created_at, updated_at, type
`

type CreateQuestionParams struct {
	ID              string `json:"id"`
	SlideID         string `json:"slide_id"`
	Index           int16  `json:"index"`
	RawQuestion     string `json:"raw_question"`
	Meta            string `json:"meta"`
	LongDescription string `json:"long_description"`
	Type            string `json:"type"`
}

func (q *Queries) CreateQuestion(ctx context.Context, arg CreateQuestionParams) (Question, error) {
	row := q.db.QueryRowContext(ctx, createQuestion,
		arg.ID,
		arg.SlideID,
		arg.Index,
		arg.RawQuestion,
		arg.Meta,
		arg.LongDescription,
		arg.Type,
	)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.SlideID,
		&i.Index,
		&i.RawQuestion,
		&i.Meta,
		&i.LongDescription,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Type,
	)
	return i, err
}

const deleteQuestion = `-- name: DeleteQuestion :exec
DELETE FROM "question" WHERE id = $1
`

func (q *Queries) DeleteQuestion(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteQuestion, id)
	return err
}

const deleteQuestionsBySlide = `-- name: DeleteQuestionsBySlide :exec
DELETE FROM "question" WHERE slide_id = $1
`

func (q *Queries) DeleteQuestionsBySlide(ctx context.Context, slideID string) error {
	_, err := q.db.ExecContext(ctx, deleteQuestionsBySlide, slideID)
	return err
}

const getOwnerOfQuestion = `-- name: GetOwnerOfQuestion :one
SELECT s.owner FROM "question" q
JOIN "slide" s ON q.slide_id = s.id
WHERE q.id = $1
`

func (q *Queries) GetOwnerOfQuestion(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getOwnerOfQuestion, id)
	var owner string
	err := row.Scan(&owner)
	return owner, err
}

const getQuestion = `-- name: GetQuestion :one
SELECT id, slide_id, index, raw_question, meta, long_description, created_at, updated_at, type FROM "question" WHERE id = $1
`

func (q *Queries) GetQuestion(ctx context.Context, id string) (Question, error) {
	row := q.db.QueryRowContext(ctx, getQuestion, id)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.SlideID,
		&i.Index,
		&i.RawQuestion,
		&i.Meta,
		&i.LongDescription,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Type,
	)
	return i, err
}

const getQuestionBySlideAndIndex = `-- name: GetQuestionBySlideAndIndex :one
SELECT id, slide_id, index, raw_question, meta, long_description, created_at, updated_at, type FROM "question" WHERE slide_id = $1 AND index = $2
`

type GetQuestionBySlideAndIndexParams struct {
	SlideID string `json:"slide_id"`
	Index   int16  `json:"index"`
}

func (q *Queries) GetQuestionBySlideAndIndex(ctx context.Context, arg GetQuestionBySlideAndIndexParams) (Question, error) {
	row := q.db.QueryRowContext(ctx, getQuestionBySlideAndIndex, arg.SlideID, arg.Index)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.SlideID,
		&i.Index,
		&i.RawQuestion,
		&i.Meta,
		&i.LongDescription,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Type,
	)
	return i, err
}

const getQuestionsBySlide = `-- name: GetQuestionsBySlide :many
SELECT id, slide_id, index, raw_question, meta, long_description, created_at, updated_at, type FROM "question" WHERE slide_id = $1
ORDER BY index ASC
`

func (q *Queries) GetQuestionsBySlide(ctx context.Context, slideID string) ([]Question, error) {
	rows, err := q.db.QueryContext(ctx, getQuestionsBySlide, slideID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Question{}
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.SlideID,
			&i.Index,
			&i.RawQuestion,
			&i.Meta,
			&i.LongDescription,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateQuestion = `-- name: UpdateQuestion :one
UPDATE "question" SET
    raw_question = $2,
    meta = $3,
    long_description = $4,
    index = $5,
    type = $6,
    updated_at = now()
WHERE id = $1
RETURNING id, slide_id, index, raw_question, meta, long_description, created_at, updated_at, type
`

type UpdateQuestionParams struct {
	ID              string `json:"id"`
	RawQuestion     string `json:"raw_question"`
	Meta            string `json:"meta"`
	LongDescription string `json:"long_description"`
	Index           int16  `json:"index"`
	Type            string `json:"type"`
}

func (q *Queries) UpdateQuestion(ctx context.Context, arg UpdateQuestionParams) (Question, error) {
	row := q.db.QueryRowContext(ctx, updateQuestion,
		arg.ID,
		arg.RawQuestion,
		arg.Meta,
		arg.LongDescription,
		arg.Index,
		arg.Type,
	)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.SlideID,
		&i.Index,
		&i.RawQuestion,
		&i.Meta,
		&i.LongDescription,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Type,
	)
	return i, err
}
