// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package entities

import (
	"database/sql"
	"time"
)

type Group struct {
	GroupID     string    `json:"group_id"`
	GroupName   string    `json:"group_name"`
	CreatedBy   string    `json:"created_by"`
	CreatedAt   time.Time `json:"created_at"`
	Description string    `json:"description"`
}

type Question struct {
	ID            string    `json:"id"`
	SlideID       string    `json:"slide_id"`
	RawQuestion   string    `json:"raw_question"`
	AnswerA       string    `json:"answer_a"`
	AnswerB       string    `json:"answer_b"`
	AnswerC       string    `json:"answer_c"`
	AnswerD       string    `json:"answer_d"`
	CorrectAnswer string    `json:"correct_answer"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type Slide struct {
	ID        string    `json:"id"`
	Owner     string    `json:"owner"`
	Title     string    `json:"title"`
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type User struct {
	UserID       string         `json:"user_id"`
	Email        string         `json:"email"`
	Name         string         `json:"name"`
	Password     string         `json:"password"`
	Verified     bool           `json:"verified"`
	VerifiedCode string         `json:"verified_code"`
	CreatedAt    time.Time      `json:"created_at"`
	GoogleID     sql.NullString `json:"google_id"`
	FacebookID   sql.NullString `json:"facebook_id"`
	AvatarUrl    string         `json:"avatar_url"`
}

type UserGroup struct {
	UserID    string    `json:"user_id"`
	GroupID   string    `json:"group_id"`
	Role      string    `json:"role"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
}
