// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package entities

import (
	"database/sql"
	"time"
)

type Group struct {
	GroupID   string    `json:"group_id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	UserID     string         `json:"user_id"`
	Email      string         `json:"email"`
	Name       string         `json:"name"`
	Password   string         `json:"password"`
	Verified   bool           `json:"verified"`
	CreatedAt  time.Time      `json:"created_at"`
	GoogleID   sql.NullString `json:"google_id"`
	FacebookID sql.NullString `json:"facebook_id"`
}

type UserGroup struct {
	UserID  string `json:"user_id"`
	GroupID string `json:"group_id"`
}
