// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package entities

import (
	"database/sql"
	"time"
)

type Answer struct {
	ID         string    `json:"id"`
	QuestionID string    `json:"question_id"`
	Index      int16     `json:"index"`
	RawAnswer  string    `json:"raw_answer"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type Group struct {
	GroupID     string    `json:"group_id"`
	GroupName   string    `json:"group_name"`
	CreatedBy   string    `json:"created_by"`
	CreatedAt   time.Time `json:"created_at"`
	Description string    `json:"description"`
}

type Question struct {
	ID              string    `json:"id"`
	SlideID         string    `json:"slide_id"`
	Index           int16     `json:"index"`
	RawQuestion     string    `json:"raw_question"`
	Meta            string    `json:"meta"`
	LongDescription string    `json:"long_description"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

type Slide struct {
	ID        string    `json:"id"`
	Owner     string    `json:"owner"`
	Title     string    `json:"title"`
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type User struct {
	UserID       string         `json:"user_id"`
	Email        string         `json:"email"`
	Name         string         `json:"name"`
	Password     string         `json:"password"`
	Verified     bool           `json:"verified"`
	VerifiedCode string         `json:"verified_code"`
	CreatedAt    time.Time      `json:"created_at"`
	GoogleID     sql.NullString `json:"google_id"`
	FacebookID   sql.NullString `json:"facebook_id"`
	AvatarUrl    string         `json:"avatar_url"`
}

type UserGroup struct {
	UserID    string    `json:"user_id"`
	GroupID   string    `json:"group_id"`
	Role      string    `json:"role"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
}
